{% set owner = "KCL-BMEIS" %}
{% set name = "spectrumdevice" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 0c29cbfdd31c0bfe313171d44f072a3479ccdf78a6e8340ffb3c52a25857b684

  - url: https://github.com/{{ owner }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: eb4a15fca6e8eb9c5a4c5c999812540a0826b9be5551706a22e7e4c59194272f
    folder: test-data

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy >=1.21.4
    - python >=3.8

test:
  imports:
    - spectrum_gmbh
    - spectrumdevice
  requires:
    - pip
    - pytest
  source_files:
    - test-data/tests
    - test-data/example_scripts
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/KCL-BMEIS/spectrumdevice
  summary: A high-level, object-oriented Python library for controlling Spectrum Instrumentation digitisers
  description: |
    spectrumdevice is a high-level, object-oriented Python library for controlling Spectrum Instrumentation digitisers.
    It can connect to individual digitisers or StarHubs (e.g. the NetBox). The main module spectrumdevice provides
    two classes SpectrumCard and SpectrumStarHub for controlling and receiving data from individual digitisers and
    StarHubs respectively. Mock classes are also provided for testing software without drivers installed or hardware
    connected.The submodule spectrumdevice.settings provides Enums and Dataclasses wrapping the register values
    provided by the Spectrum API, to be used for configuring hardware and interpreting responses received from hardware.
  doc_url: https://kcl-bmeis.github.io/spectrumdevice/
  dev_url: https://github.com/KCL-BMEIS/spectrumdevice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crnbaker
